/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *r0c0;
    QPushButton *r1c0;
    QPushButton *r2c0;
    QPushButton *r3c0;
    QPushButton *r4c0;
    QPushButton *r5c0;
    QPushButton *r6c0;
    QPushButton *r7c0;
    QPushButton *r1c1;
    QPushButton *r3c1;
    QPushButton *r2c1;
    QPushButton *r6c1;
    QPushButton *r4c1;
    QPushButton *r5c1;
    QPushButton *r0c1;
    QPushButton *r7c1;
    QPushButton *r4c3;
    QPushButton *r1c2;
    QPushButton *r3c2;
    QPushButton *r2c2;
    QPushButton *r6c2;
    QPushButton *r1c3;
    QPushButton *r4c2;
    QPushButton *r3c3;
    QPushButton *r6c3;
    QPushButton *r2c3;
    QPushButton *r7c3;
    QPushButton *r5c2;
    QPushButton *r5c3;
    QPushButton *r0c2;
    QPushButton *r7c2;
    QPushButton *r0c3;
    QPushButton *r3c5;
    QPushButton *r4c7;
    QPushButton *r3c7;
    QPushButton *r6c5;
    QPushButton *r3c6;
    QPushButton *r4c5;
    QPushButton *r0c7;
    QPushButton *r0c5;
    QPushButton *r7c4;
    QPushButton *r1c4;
    QPushButton *r6c4;
    QPushButton *r4c6;
    QPushButton *r2c5;
    QPushButton *r1c6;
    QPushButton *r7c5;
    QPushButton *r5c7;
    QPushButton *r5c5;
    QPushButton *r6c7;
    QPushButton *r7c7;
    QPushButton *r2c6;
    QPushButton *r1c5;
    QPushButton *r0c6;
    QPushButton *r3c4;
    QPushButton *r2c7;
    QPushButton *r6c6;
    QPushButton *r2c4;
    QPushButton *r7c6;
    QPushButton *r4c4;
    QPushButton *r1c7;
    QPushButton *r5c6;
    QPushButton *r5c4;
    QPushButton *r0c4;
    QLabel *Player1;
    QLabel *Player2;
    QPushButton *sign;
    QLabel *blackcnt;
    QLabel *whitecnt;
    QLabel *turn;
    QLabel *countdown;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(260, 330);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        r0c0 = new QPushButton(centralWidget);
        r0c0->setObjectName(QStringLiteral("r0c0"));
        r0c0->setGeometry(QRect(10, 80, 30, 30));
        r0c0->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r1c0 = new QPushButton(centralWidget);
        r1c0->setObjectName(QStringLiteral("r1c0"));
        r1c0->setGeometry(QRect(10, 110, 30, 30));
        r1c0->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r2c0 = new QPushButton(centralWidget);
        r2c0->setObjectName(QStringLiteral("r2c0"));
        r2c0->setGeometry(QRect(10, 140, 30, 30));
        r2c0->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r3c0 = new QPushButton(centralWidget);
        r3c0->setObjectName(QStringLiteral("r3c0"));
        r3c0->setGeometry(QRect(10, 170, 30, 30));
        r3c0->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r4c0 = new QPushButton(centralWidget);
        r4c0->setObjectName(QStringLiteral("r4c0"));
        r4c0->setGeometry(QRect(10, 200, 30, 30));
        r4c0->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r5c0 = new QPushButton(centralWidget);
        r5c0->setObjectName(QStringLiteral("r5c0"));
        r5c0->setGeometry(QRect(10, 230, 30, 30));
        r5c0->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r6c0 = new QPushButton(centralWidget);
        r6c0->setObjectName(QStringLiteral("r6c0"));
        r6c0->setGeometry(QRect(10, 260, 30, 30));
        r6c0->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r7c0 = new QPushButton(centralWidget);
        r7c0->setObjectName(QStringLiteral("r7c0"));
        r7c0->setGeometry(QRect(10, 290, 30, 30));
        r7c0->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r1c1 = new QPushButton(centralWidget);
        r1c1->setObjectName(QStringLiteral("r1c1"));
        r1c1->setGeometry(QRect(40, 110, 30, 30));
        r1c1->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r3c1 = new QPushButton(centralWidget);
        r3c1->setObjectName(QStringLiteral("r3c1"));
        r3c1->setGeometry(QRect(40, 170, 30, 30));
        r3c1->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r2c1 = new QPushButton(centralWidget);
        r2c1->setObjectName(QStringLiteral("r2c1"));
        r2c1->setGeometry(QRect(40, 140, 30, 30));
        r2c1->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r6c1 = new QPushButton(centralWidget);
        r6c1->setObjectName(QStringLiteral("r6c1"));
        r6c1->setGeometry(QRect(40, 260, 30, 30));
        r6c1->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r4c1 = new QPushButton(centralWidget);
        r4c1->setObjectName(QStringLiteral("r4c1"));
        r4c1->setGeometry(QRect(40, 200, 30, 30));
        r4c1->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r5c1 = new QPushButton(centralWidget);
        r5c1->setObjectName(QStringLiteral("r5c1"));
        r5c1->setGeometry(QRect(40, 230, 30, 30));
        r5c1->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r0c1 = new QPushButton(centralWidget);
        r0c1->setObjectName(QStringLiteral("r0c1"));
        r0c1->setGeometry(QRect(40, 80, 30, 30));
        r0c1->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r7c1 = new QPushButton(centralWidget);
        r7c1->setObjectName(QStringLiteral("r7c1"));
        r7c1->setGeometry(QRect(40, 290, 30, 30));
        r7c1->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r4c3 = new QPushButton(centralWidget);
        r4c3->setObjectName(QStringLiteral("r4c3"));
        r4c3->setGeometry(QRect(100, 200, 30, 30));
        r4c3->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(0, 0, 0);border-radius: 3px} QPushButton:hover { background-color: rgb(0, 0, 0); }"));
        r1c2 = new QPushButton(centralWidget);
        r1c2->setObjectName(QStringLiteral("r1c2"));
        r1c2->setGeometry(QRect(70, 110, 30, 30));
        r1c2->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r3c2 = new QPushButton(centralWidget);
        r3c2->setObjectName(QStringLiteral("r3c2"));
        r3c2->setGeometry(QRect(70, 170, 30, 30));
        r3c2->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r2c2 = new QPushButton(centralWidget);
        r2c2->setObjectName(QStringLiteral("r2c2"));
        r2c2->setGeometry(QRect(70, 140, 30, 30));
        r2c2->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r6c2 = new QPushButton(centralWidget);
        r6c2->setObjectName(QStringLiteral("r6c2"));
        r6c2->setGeometry(QRect(70, 260, 30, 30));
        r6c2->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r1c3 = new QPushButton(centralWidget);
        r1c3->setObjectName(QStringLiteral("r1c3"));
        r1c3->setGeometry(QRect(100, 110, 30, 30));
        r1c3->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r4c2 = new QPushButton(centralWidget);
        r4c2->setObjectName(QStringLiteral("r4c2"));
        r4c2->setGeometry(QRect(70, 200, 30, 30));
        r4c2->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r3c3 = new QPushButton(centralWidget);
        r3c3->setObjectName(QStringLiteral("r3c3"));
        r3c3->setGeometry(QRect(100, 170, 30, 30));
        r3c3->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(255, 255, 255);border-radius: 3px} QPushButton:hover { background-color: rgb(255, 255, 255); }"));
        r6c3 = new QPushButton(centralWidget);
        r6c3->setObjectName(QStringLiteral("r6c3"));
        r6c3->setGeometry(QRect(100, 260, 30, 30));
        r6c3->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r2c3 = new QPushButton(centralWidget);
        r2c3->setObjectName(QStringLiteral("r2c3"));
        r2c3->setGeometry(QRect(100, 140, 30, 30));
        r2c3->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r7c3 = new QPushButton(centralWidget);
        r7c3->setObjectName(QStringLiteral("r7c3"));
        r7c3->setGeometry(QRect(100, 290, 30, 30));
        r7c3->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r5c2 = new QPushButton(centralWidget);
        r5c2->setObjectName(QStringLiteral("r5c2"));
        r5c2->setGeometry(QRect(70, 230, 30, 30));
        r5c2->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r5c3 = new QPushButton(centralWidget);
        r5c3->setObjectName(QStringLiteral("r5c3"));
        r5c3->setGeometry(QRect(100, 230, 30, 30));
        r5c3->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r0c2 = new QPushButton(centralWidget);
        r0c2->setObjectName(QStringLiteral("r0c2"));
        r0c2->setGeometry(QRect(70, 80, 30, 30));
        r0c2->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r7c2 = new QPushButton(centralWidget);
        r7c2->setObjectName(QStringLiteral("r7c2"));
        r7c2->setGeometry(QRect(70, 290, 30, 30));
        r7c2->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r0c3 = new QPushButton(centralWidget);
        r0c3->setObjectName(QStringLiteral("r0c3"));
        r0c3->setGeometry(QRect(100, 80, 30, 30));
        r0c3->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r3c5 = new QPushButton(centralWidget);
        r3c5->setObjectName(QStringLiteral("r3c5"));
        r3c5->setGeometry(QRect(160, 170, 30, 30));
        r3c5->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r4c7 = new QPushButton(centralWidget);
        r4c7->setObjectName(QStringLiteral("r4c7"));
        r4c7->setGeometry(QRect(220, 200, 30, 30));
        r4c7->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r3c7 = new QPushButton(centralWidget);
        r3c7->setObjectName(QStringLiteral("r3c7"));
        r3c7->setGeometry(QRect(220, 170, 30, 30));
        r3c7->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r6c5 = new QPushButton(centralWidget);
        r6c5->setObjectName(QStringLiteral("r6c5"));
        r6c5->setGeometry(QRect(160, 260, 30, 30));
        r6c5->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r3c6 = new QPushButton(centralWidget);
        r3c6->setObjectName(QStringLiteral("r3c6"));
        r3c6->setGeometry(QRect(190, 170, 30, 30));
        r3c6->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r4c5 = new QPushButton(centralWidget);
        r4c5->setObjectName(QStringLiteral("r4c5"));
        r4c5->setGeometry(QRect(160, 200, 30, 30));
        r4c5->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r0c7 = new QPushButton(centralWidget);
        r0c7->setObjectName(QStringLiteral("r0c7"));
        r0c7->setGeometry(QRect(220, 80, 30, 30));
        r0c7->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r0c5 = new QPushButton(centralWidget);
        r0c5->setObjectName(QStringLiteral("r0c5"));
        r0c5->setGeometry(QRect(160, 80, 30, 30));
        r0c5->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r7c4 = new QPushButton(centralWidget);
        r7c4->setObjectName(QStringLiteral("r7c4"));
        r7c4->setGeometry(QRect(130, 290, 30, 30));
        r7c4->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r1c4 = new QPushButton(centralWidget);
        r1c4->setObjectName(QStringLiteral("r1c4"));
        r1c4->setGeometry(QRect(130, 110, 30, 30));
        r1c4->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r6c4 = new QPushButton(centralWidget);
        r6c4->setObjectName(QStringLiteral("r6c4"));
        r6c4->setGeometry(QRect(130, 260, 30, 30));
        r6c4->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r4c6 = new QPushButton(centralWidget);
        r4c6->setObjectName(QStringLiteral("r4c6"));
        r4c6->setGeometry(QRect(190, 200, 30, 30));
        r4c6->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r2c5 = new QPushButton(centralWidget);
        r2c5->setObjectName(QStringLiteral("r2c5"));
        r2c5->setGeometry(QRect(160, 140, 30, 30));
        r2c5->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r1c6 = new QPushButton(centralWidget);
        r1c6->setObjectName(QStringLiteral("r1c6"));
        r1c6->setGeometry(QRect(190, 110, 30, 30));
        r1c6->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r7c5 = new QPushButton(centralWidget);
        r7c5->setObjectName(QStringLiteral("r7c5"));
        r7c5->setGeometry(QRect(160, 290, 30, 30));
        r7c5->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r5c7 = new QPushButton(centralWidget);
        r5c7->setObjectName(QStringLiteral("r5c7"));
        r5c7->setGeometry(QRect(220, 230, 30, 30));
        r5c7->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r5c5 = new QPushButton(centralWidget);
        r5c5->setObjectName(QStringLiteral("r5c5"));
        r5c5->setGeometry(QRect(160, 230, 30, 30));
        r5c5->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r6c7 = new QPushButton(centralWidget);
        r6c7->setObjectName(QStringLiteral("r6c7"));
        r6c7->setGeometry(QRect(220, 260, 30, 30));
        r6c7->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r7c7 = new QPushButton(centralWidget);
        r7c7->setObjectName(QStringLiteral("r7c7"));
        r7c7->setGeometry(QRect(220, 290, 30, 30));
        r7c7->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r2c6 = new QPushButton(centralWidget);
        r2c6->setObjectName(QStringLiteral("r2c6"));
        r2c6->setGeometry(QRect(190, 140, 30, 30));
        r2c6->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r1c5 = new QPushButton(centralWidget);
        r1c5->setObjectName(QStringLiteral("r1c5"));
        r1c5->setGeometry(QRect(160, 110, 30, 30));
        r1c5->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r0c6 = new QPushButton(centralWidget);
        r0c6->setObjectName(QStringLiteral("r0c6"));
        r0c6->setGeometry(QRect(190, 80, 30, 30));
        r0c6->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r3c4 = new QPushButton(centralWidget);
        r3c4->setObjectName(QStringLiteral("r3c4"));
        r3c4->setGeometry(QRect(130, 170, 30, 30));
        r3c4->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(0, 0, 0);border-radius: 3px} QPushButton:hover { background-color: rgb(0, 0, 0); }"));
        r2c7 = new QPushButton(centralWidget);
        r2c7->setObjectName(QStringLiteral("r2c7"));
        r2c7->setGeometry(QRect(220, 140, 30, 30));
        r2c7->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r6c6 = new QPushButton(centralWidget);
        r6c6->setObjectName(QStringLiteral("r6c6"));
        r6c6->setGeometry(QRect(190, 260, 30, 30));
        r6c6->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r2c4 = new QPushButton(centralWidget);
        r2c4->setObjectName(QStringLiteral("r2c4"));
        r2c4->setGeometry(QRect(130, 140, 30, 30));
        r2c4->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r7c6 = new QPushButton(centralWidget);
        r7c6->setObjectName(QStringLiteral("r7c6"));
        r7c6->setGeometry(QRect(190, 290, 30, 30));
        r7c6->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r4c4 = new QPushButton(centralWidget);
        r4c4->setObjectName(QStringLiteral("r4c4"));
        r4c4->setGeometry(QRect(130, 200, 30, 30));
        r4c4->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(255, 255, 255);border-radius: 3px} QPushButton:hover { background-color: rgb(255, 255, 255); }"));
        r1c7 = new QPushButton(centralWidget);
        r1c7->setObjectName(QStringLiteral("r1c7"));
        r1c7->setGeometry(QRect(220, 110, 30, 30));
        r1c7->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r5c6 = new QPushButton(centralWidget);
        r5c6->setObjectName(QStringLiteral("r5c6"));
        r5c6->setGeometry(QRect(190, 230, 30, 30));
        r5c6->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r5c4 = new QPushButton(centralWidget);
        r5c4->setObjectName(QStringLiteral("r5c4"));
        r5c4->setGeometry(QRect(130, 230, 30, 30));
        r5c4->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        r0c4 = new QPushButton(centralWidget);
        r0c4->setObjectName(QStringLiteral("r0c4"));
        r0c4->setGeometry(QRect(130, 80, 30, 30));
        r0c4->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(200, 200, 200);border-radius: 3px} QPushButton:hover { background-color: rgb(230, 230, 230); }"));
        Player1 = new QLabel(centralWidget);
        Player1->setObjectName(QStringLiteral("Player1"));
        Player1->setGeometry(QRect(10, 10, 81, 30));
        Player1->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        Player1->setAlignment(Qt::AlignCenter);
        Player2 = new QLabel(centralWidget);
        Player2->setObjectName(QStringLiteral("Player2"));
        Player2->setGeometry(QRect(170, 10, 81, 30));
        Player2->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        Player2->setAlignment(Qt::AlignCenter);
        sign = new QPushButton(centralWidget);
        sign->setObjectName(QStringLiteral("sign"));
        sign->setGeometry(QRect(97, 10, 30, 30));
        sign->setStyleSheet(QStringLiteral("QPushButton { background-color: rgb(0, 0, 0);border-radius: 3px} QPushButton:hover { background-color: rgb(0, 0, 0); }"));
        blackcnt = new QLabel(centralWidget);
        blackcnt->setObjectName(QStringLiteral("blackcnt"));
        blackcnt->setGeometry(QRect(10, 40, 81, 41));
        blackcnt->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        blackcnt->setAlignment(Qt::AlignCenter);
        whitecnt = new QLabel(centralWidget);
        whitecnt->setObjectName(QStringLiteral("whitecnt"));
        whitecnt->setGeometry(QRect(170, 40, 81, 41));
        whitecnt->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        whitecnt->setAlignment(Qt::AlignCenter);
        turn = new QLabel(centralWidget);
        turn->setObjectName(QStringLiteral("turn"));
        turn->setGeometry(QRect(130, 20, 40, 16));
        countdown = new QLabel(centralWidget);
        countdown->setObjectName(QStringLiteral("countdown"));
        countdown->setGeometry(QRect(102, 40, 60, 40));
        QFont font;
        font.setPointSize(15);
        countdown->setFont(font);
        countdown->setAlignment(Qt::AlignCenter);
        MainWindow->setCentralWidget(centralWidget);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        r0c0->setText(QString());
        r1c0->setText(QString());
        r2c0->setText(QString());
        r3c0->setText(QString());
        r4c0->setText(QString());
        r5c0->setText(QString());
        r6c0->setText(QString());
        r7c0->setText(QString());
        r1c1->setText(QString());
        r3c1->setText(QString());
        r2c1->setText(QString());
        r6c1->setText(QString());
        r4c1->setText(QString());
        r5c1->setText(QString());
        r0c1->setText(QString());
        r7c1->setText(QString());
        r4c3->setText(QString());
        r1c2->setText(QString());
        r3c2->setText(QString());
        r2c2->setText(QString());
        r6c2->setText(QString());
        r1c3->setText(QString());
        r4c2->setText(QString());
        r3c3->setText(QString());
        r6c3->setText(QString());
        r2c3->setText(QString());
        r7c3->setText(QString());
        r5c2->setText(QString());
        r5c3->setText(QString());
        r0c2->setText(QString());
        r7c2->setText(QString());
        r0c3->setText(QString());
        r3c5->setText(QString());
        r4c7->setText(QString());
        r3c7->setText(QString());
        r6c5->setText(QString());
        r3c6->setText(QString());
        r4c5->setText(QString());
        r0c7->setText(QString());
        r0c5->setText(QString());
        r7c4->setText(QString());
        r1c4->setText(QString());
        r6c4->setText(QString());
        r4c6->setText(QString());
        r2c5->setText(QString());
        r1c6->setText(QString());
        r7c5->setText(QString());
        r5c7->setText(QString());
        r5c5->setText(QString());
        r6c7->setText(QString());
        r7c7->setText(QString());
        r2c6->setText(QString());
        r1c5->setText(QString());
        r0c6->setText(QString());
        r3c4->setText(QString());
        r2c7->setText(QString());
        r6c6->setText(QString());
        r2c4->setText(QString());
        r7c6->setText(QString());
        r4c4->setText(QString());
        r1c7->setText(QString());
        r5c6->setText(QString());
        r5c4->setText(QString());
        r0c4->setText(QString());
        Player1->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Black</span></p></body></html>", Q_NULLPTR));
        Player2->setText(QApplication::translate("MainWindow", "White", Q_NULLPTR));
        sign->setText(QString());
        blackcnt->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">2</span></p></body></html>", Q_NULLPTR));
        whitecnt->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">2</span></p></body></html>", Q_NULLPTR));
        turn->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">\345\233\236\345\220\210</span></p></body></html>", Q_NULLPTR));
        countdown->setText(QApplication::translate("MainWindow", "60", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
